import { User, Carrera, Justificante } from './types';

export const carreras: Carrera[] = [
  { id: '1', nombre: 'Ingeniería en Software', abreviatura: 'ISW' },
  { id: '2', nombre: 'Ingeniería en Biotecnología', abreviatura: 'IBT' },
  { id: '3', nombre: 'Ingeniería en Redes y Telecomunicaciones', abreviatura: 'IRT' },
  { id: '4', nombre: 'Licenciatura en Administración y Gestión Empresarial', abreviatura: 'LAGE' },
  { id: '5', nombre: 'Ingeniería Financiera', abreviatura: 'IF' },
  { id: '6', nombre: 'Licenciatura en Terapia Física', abreviatura: 'LTF' },
  { id: '7', nombre: 'Ingeniería en Animación y Efectos Visuales', abreviatura: 'IAEV' },
  { id: '8', nombre: 'Ingeniería en Energía', abreviatura: 'IE' },
];

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'juan.perez@upqroo.edu.mx',
    nombre: 'Juan Carlos',
    apellidos: 'Pérez López',
    rol: 'alumno',
    carrera: 'Ingeniería en Software',
    semestre: 5,
    matricula: '20210001',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=JP',
    perfilCompleto: true,
  },
  {
    id: '2',
    email: 'maria.garcia@upqroo.edu.mx',
    nombre: 'María Fernanda',
    apellidos: 'García Hernández',
    rol: 'alumno',
    carrera: 'Ingeniería en Software',
    semestre: 3,
    matricula: '20210045',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=MG',
    perfilCompleto: true,
  },
  {
    id: '3',
    email: 'carlos.mendez@upqroo.edu.mx',
    nombre: 'Carlos Alberto',
    apellidos: 'Méndez Ruiz',
    rol: 'alumno',
    carrera: 'Ingeniería en Biotecnología',
    semestre: 7,
    matricula: '20200123',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=CM',
    perfilCompleto: true,
  },
  {
    id: '4',
    email: 'ana.rodriguez@upqroo.edu.mx',
    nombre: 'Ana Sofía',
    apellidos: 'Rodríguez Castillo',
    rol: 'profesor',
    carrera: 'Ingeniería en Software',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=AR',
  },
  {
    id: '5',
    email: 'roberto.sanchez@upqroo.edu.mx',
    nombre: 'Roberto',
    apellidos: 'Sánchez Mora',
    rol: 'coordinador',
    carrera: 'Ingeniería en Software',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=RS',
  },
  {
    id: '6',
    email: 'laura.martinez@upqroo.edu.mx',
    nombre: 'Laura Elena',
    apellidos: 'Martínez Vega',
    rol: 'coordinador',
    carrera: 'Ingeniería en Biotecnología',
    imagen: 'https://api.dicebear.com/7.x/initials/svg?seed=LM',
  },
];

export const mockJustificantes: Justificante[] = [
  {
    id: '1',
    alumnoId: '1',
    alumno: mockUsers[0],
    fechaInicio: '2026-01-15',
    fechaFin: '2026-01-15',
    fechaCreacion: '2026-01-16',
    motivo: 'Cita médica',
    descripcion: 'Cita de seguimiento con especialista en el Hospital General.',
    archivoNombre: 'constancia_medica.pdf',
    status: 'aprobado',
    carrera: 'Ingeniería en Software',
  },
  {
    id: '2',
    alumnoId: '1',
    alumno: mockUsers[0],
    fechaInicio: '2026-01-10',
    fechaFin: '2026-01-12',
    fechaCreacion: '2026-01-10',
    motivo: 'Enfermedad',
    descripcion: 'Cuadro gripal con fiebre alta.',
    archivoNombre: 'receta_medica.pdf',
    status: 'aprobado',
    carrera: 'Ingeniería en Software',
  },
  {
    id: '3',
    alumnoId: '2',
    alumno: mockUsers[1],
    fechaInicio: '2026-01-18',
    fechaFin: '2026-01-18',
    fechaCreacion: '2026-01-18',
    motivo: 'Trámite oficial',
    descripcion: 'Renovación de pasaporte en oficinas de SRE.',
    archivoNombre: 'comprobante_cita.pdf',
    status: 'pendiente',
    carrera: 'Ingeniería en Software',
  },
  {
    id: '4',
    alumnoId: '3',
    alumno: mockUsers[2],
    fechaInicio: '2026-01-12',
    fechaFin: '2026-01-14',
    fechaCreacion: '2026-01-13',
    motivo: 'Emergencia familiar',
    descripcion: 'Fallecimiento de familiar cercano.',
    archivoNombre: 'acta_defuncion.pdf',
    status: 'aprobado',
    carrera: 'Ingeniería en Biotecnología',
  },
  {
    id: '5',
    alumnoId: '2',
    alumno: mockUsers[1],
    fechaInicio: '2026-01-05',
    fechaFin: '2026-01-07',
    fechaCreacion: '2026-01-06',
    motivo: 'Representación deportiva',
    descripcion: 'Participación en torneo universitario estatal de voleibol.',
    archivoNombre: 'oficio_deportes.pdf',
    status: 'aprobado',
    carrera: 'Ingeniería en Software',
  },
];

// Simula el usuario actual (cambiar para probar diferentes roles)
export const currentUser: User = mockUsers[0]; // Alumno por defecto

// Función para cambiar el usuario mock (útil para testing)
export function getMockUserByRole(role: 'alumno' | 'profesor' | 'coordinador'): User {
  return mockUsers.find(u => u.rol === role) || mockUsers[0];
}
